name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add .html extensions
        run: |
          cd public
          for f in *; do
            [[ "$f" == *.* ]] || mv "$f" "$f.html"
          done

      - name: Fix index.html hrefs
        run: sed -i 's|href="\([^"#.:]*\)"|href="\1.html"|g' public/index.html

      - name: Deploy /public to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages